# -*- coding: utf-8 -*-
"""Youtube2Speech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11k-Jm6p_tTfwQNa0Uelbh50hVIeAGkIj

<h1>
    Youtube2Speech 
    <a href="https://github.com/1nj3ct0rrr/Youtube2Speech">
        <img src="https://img.shields.io/badge/GitHub-black?style=flat&logo=github&labelColor=black">
    </a>
</h1>

This noteboo uses an [open source project](https://github.com/mozilla/DeepSpeech) to transcribe a given Youtube video 😄

## Install DeepSpeech
"""

import os
from os.path import exists, join, basename, splitext

if not exists('deepspeech-0.6.1-models'):
  !apt-get install -qq sox
  !pip install -q deepspeech-gpu==0.6.1 youtube-dl
  !wget https://github.com/mozilla/DeepSpeech/releases/download/v0.6.1/deepspeech-0.6.1-models.tar.gz

  !tar xvfz deepspeech-0.6.1-models.tar.gz
  
from IPython.display import YouTubeVideo

"""## Transcribe Youtube Video

We are going to make speech recognition on the following Youtube video:
"""

YOUTUBE_ID = 'e5nlD2LfGd0'

YouTubeVideo(YOUTUBE_ID)

"""Download the above video, convert to a WAV file and do speech recognition 🙂🙃"""

!rm -rf *.wav
!youtube-dl --extract-audio --audio-format wav --output "test.%(ext)s" https://www.youtube.com/watch\?v\={YOUTUBE_ID}
!deepspeech --model deepspeech-0.6.1-models/output_graph.pbmm --lm deepspeech-0.6.1-models/lm.binary --trie deepspeech-0.6.1-models/trie --audio test.wav

"""## Follow Me

<p>
 <a href="https://repl.it/@hesamtavakoli06">
  <img src="https://img.shields.io/badge/Repl.it-gray?style=flat&logo=repl.it&labelColor=gray">
 </a>
</p>

<p>
 <a href="https://github.com/1nj3ct0rrr">
  <img src="https://img.shields.io/badge/GitHub-black?style=flat&logo=github&labelColor=black">
 </a>
</p>

<p>
 <a href="https://codepen.io/1nj3ct0r">
  <img src="https://img.shields.io/badge/CodePen-black?style=flat&logo=codepen&labelColor=black">
 </a>
</p>

<p>
 <a href="https://linkedin.com/in/1nj3ct0r">
  <img src="https://img.shields.io/badge/LinkedIn-blue?style=flat&logo=linkedin&labelColor=blue">
 </a>
</p>

<p>
 <a href="https://leetcode.com/1nj3ct0r/">
  <img src="https://img.shields.io/badge/LeetCode-white?style=flat&logo=leetcode&labelColor=white">
 </a>
</p>

<p>
 <a href="https://www.hackerrank.com/1nj3ct0r">
  <img src="https://img.shields.io/badge/HackerRank-black?style=flat&logo=hackerrank&labelColor=black">
 </a>
</p>

"""